#!/bin/sh

case $1 in

vol)

	case $2 in
	up)
		amixer -q set Master 5%+ ;;
	down)
		amixer -q set Master 5%- ;;
	toggle)
		amixer -q set Master toggle ;;
	*)
		exit 1 ;;
	esac
	;;

*)
	;;

esac

tstat set
